[workspace]
members = ["infrastructure", "twitch-bot", "server"]

[workspace.package]
description = "A silly minigame about drinking NOT milk."
version = "1.0.0"
authors = ["ilotterytea <ilotterytea@pm.me>"]
edition = "2021"
publish = false
repository = "https://github.com/ilotterytea/not-milk"
