name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check (Ubuntu)
    steps:
    - uses: actions/checkout@v3
    - run: rustup default nightly
    - run: cargo check --verbose
    
  clippy:
    runs-on: ubuntu-latest
    name: Clippy (Ubuntu)
    steps:
    - uses: actions/checkout@v3
    - run: rustup default nightly
    - run: rustup component add clippy
    - run: cargo clippy -- -D warnings -A clippy::type-complexity --verbose 
